### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by BrycensRanch** [GooglyBlox/wizard-quotes#1]
This code uses 2.3GB of memory on my machine.

**Comment by GooglyBlox** [comment]
Don't care, Linux skill issue, use a better kernel, works on my machine.

**Comment by BrycensRanch** [comment]
> Don't care, Linux skill issue, use a better kernel, works on my machine.

bloated chatgpt ahhh repository 😤

**Comment by GooglyBlox** [comment]
let me use my tailwind in peace lil bro 😭🙏
